### ISSUE TITLE
Wrong parsing via XSAMPA

### ISSUE THREAD

**Issue by Schweikhard** [digling/edictor#159] opened 2018-04-23 07:56 UTC
Some XSAMPA-shortcuts turn into the wrong character:

& should become ɶ but turns into æ
m_0 should become m̥, but turns into m₀ (same with other nasals and liquids)
m_= should become m̩ but turns into m ̍ (same with other nasals and liquids)
u_^ or u^ should become ʊ̯ but turns into ʊ_↑ or ʊ↑ (same with other vowels)

Some don't work at all:

{ and } should become æ and ʉ but remain { and }.

I've tested all vowel shortcuts but only a handful of consonant and diacritic shortcuts thus far.

**Comment by LinguList** [comment] 2018-04-23 14:50
Yes, there are certain cases where the mapping script is not right, just checked and verified. Could you start assembling a systematic table? If we have it, it will be easier to replace the problematic cases (e.g.: tab-separated file, source-target column). Note that we have some further extensions, not necessarily an immediate wonder that some things work, differently, e.g., _0 becoming ₀, as it follows our tone logic.  But ideally, we'll provide a full mapping table for beginners who want to learn the sampa system, etc.

**Comment by LinguList** [comment] 2018-04-23 14:55
I suggest, we take this side as first reference http://www.lfsag.unito.it/ipa/index_en.html
And then we take lingpy's csv-sheet as the one to be corrected: https://github.com/lingpy/lingpy/blob/master/lingpy/data/ipa/sampa.csv

**Comment by Schweikhard** [comment] 2018-04-23 14:57
You mean, one column XSAMPA-shortcut, one column intended IPA-outcome? There's a table here: https://en.wikipedia.org/wiki/X-SAMPA#Lower_case_symbols

**Comment by LinguList** [comment] 2018-04-23 14:59
We have an extended table in lingpy with additional shortcuts useful (_1 becomes ```¹```, etc.), so all changes should address, correct, and enhance our lingpy-table (link above). Taking the wiki-table as starting point is also a good idea.

**Comment by Schweikhard** [comment] 2018-04-23 14:59
Needs to be put into the proper format of course, and doesn't include the diacritics.

**Comment by LinguList** [comment] 2018-04-23 15:01
Yes, so let's start from our lingpy table, and since we'll re-work on x-sampa anyway for the [clts](https://github.com/cldf/clts) project anyway, we'll do good in using one central place where to put our mapping. Starting from the lingpy-file is probably the best idea, as it is the one that edictor was built upon, and it is rather okay...

**Comment by Schweikhard** [comment] 2018-04-23 15:04
That lingpy table doesn't seem to contain the mistakes I found, though. Or am I misunderstanding something?

**Comment by LinguList** [comment] 2018-04-23 15:05
possible.

**Comment by Schweikhard** [comment] 2018-04-23 15:10
If the lingpy table is what Edictor was built on, then mistakes in Edictor should also be found in the table, shouldn't they?

**Comment by LinguList** [comment] 2018-04-23 15:11
Honestly, I don't recall what code I based the edictor version upon, maybe it wasn't that lingpy thing. But I have the table, it's just looking cryptic, as it is javascript code, so pasting it here is not that a good idea. So I suppose we leave this issue open up to the point where we introduce the clts-x-sampa, where the problems will be fixed.

**Comment by LinguList** [comment] 2018-04-23 15:12
So there are two questions: a) edictor is currently not doing all that is expected in x-sampa, b) we want to work on a general x-sampa mapper that is included into a bigger library.

So it is easiest to work on the general thing, starting from lingpy (as this one is more or less authoritative), and then building this into edictor.

**Comment by Schweikhard** [comment] 2018-04-23 15:13
agreed

**Comment by LinguList** [comment] 2018-04-23 15:13
[sampa.js.txt](https://github.com/digling/edictor/files/1938868/sampa.js.txt)

this is the table in edictor. the array (in first lines of script) reads like "source" : "target"

**Comment by LinguList** [comment] 2018-04-24 04:33
@tresoldi, this is just to ping you in as well, since we should try and use a common version of X-Sampa (adding some modifications that we'll often use, following the [bxs table](https://github.com/bpj/bpj-vim-keymaps/blob/master/keymap/bxs.vim), which I find quite useful. For the time being, let's collect some bugs in edictor here, preferably in a text-file, so I can already add them to the code for the time being, to avoid that certain characters are a pain in the neck to type, but the issue is definitely more general than this.

**Closed** 2024-06-09 05:26 UTC
Labels: specific features, refactoring
