### ISSUE TITLE
edictor wordlist not available

### ISSUE THREAD

**Issue by FredericBlum** [digling/edictor#224] opened 2024-10-11 07:27 UTC
If I try to run `edictor wordlist` with EDICTOR3, I receive the following error message:

```bash
(edictor) frederic@frederics-MacBook-Air blumpanoyanomamic % edictor wordlist --dataset=cldf/cldf/metadata.json --name=blumpanoyanomamic --sqlite
usage: edictor [-h] {server,fetch} ...
edictor: error: argument subcommand: invalid choice: 'wordlist' (choose from 'server', 'fetch')
(edictor) frederic@frederics-MacBook-Air blumpanoyanomamic % edictor -h
usage: edictor [-h] {server,fetch} ...

Computer-assisted language comparison with EDICTOR 3.

positional arguments:
  {server,fetch}
    server        Run EDICTOR 3 in a local server and access the application through your webbrowser.
    fetch         Download a wordlist from an EDICTOR application.

optional arguments:
  -h, --help      show this help message and exit
```

This is with the install directly from the git-repo, so it shoul dbe the most recent version. What am I missing?

**Comment by LinguList** [comment] 2024-10-11 22:24
You are missing requirements.

**Comment by LinguList** [comment] 2024-10-11 22:25
https://github.com/digling/edictor/?tab=readme-ov-file#installing-edictor-3-with-lingpy-support

**Comment by LinguList** [comment] 2024-10-11 22:25
This addresses the question and should solve the problem.

**Comment by FredericBlum** [comment] 2024-10-14 08:05
It does! I have to run an extra command though to install lingpy, because I receive the following error message:

```bash
(edictor) blum@lingn45w Projects % pip install edictor[lingpy]     
zsh: no matches found: edictor[lingpy]
```

I can run `pip install lingpy` though and then the wordlist-functionality becomes available.

**Comment by FredericBlum** [comment] 2024-10-14 08:23
But the reason I had used the other approach was that I do not know how I can use `edictor wordlist` to get additional columns. I looked at the code in `src/edictor/cli.py`, but I can't seem to figure out the correct form of adding the json-style columns, e.g. `edictor wordlist --dataset=cldf/cldf-metadata.json --name=blumpanoyanomamic --sqlite --namespace='{"source_concept": "source_concept"}'`

**Comment by LinguList** [comment] 2024-10-14 21:48
You can most easily just add the columns inside lingpy, as shown [here](https://calc.hypotheses.org/4432). But the namespace is basically as the help function says:

```
edictor wordlist -h
```

```
...
  --namespace NAMESPACE
                        namespace and columns you want to extract (default: {"language_id": "doculect", "concept_name":
                        "concept","value": "value", "form": "form", "segments": "tokens","comment": "note"})
...
```

**Comment by LinguList** [comment] 2024-10-14 21:50
The problem is we convert several tables in CLDF to one table in lingpy/edictor. So we map the column names from the individualfiles to one new name in the resulting TSV. `language_id` is from `languges.csv`. `concept_name` is from `parameters.csv`, and the rest is from `forms.csv`. This is not well documented, but also usually not used.

**Comment by LinguList** [comment] 2024-10-14 21:50
What columns of the CLDF do you want to map to the TSV? Let us start from there.

**Comment by LinguList** [comment] 2024-10-14 21:53
> It does! I have to run an extra command though to install lingpy, because I receive the following error message:
> 
> ```shell
> (edictor) blum@lingn45w Projects % pip install edictor[lingpy]     
> zsh: no matches found: edictor[lingpy]
> ```
> 
> I can run `pip install lingpy` though and then the wordlist-functionality becomes available.

That this does *not* work surprises me. I think it even works on windows (but has been some time I tested there). To run correctly, run: 
```
pip install -r requirements.txt
```
from within the edictor version. Or run `pip install lexibase lingpy edictor`

**Comment by LinguList** [comment] 2024-10-14 21:54
```
pip install lexibase lingpy lingrex edictor
```
Those are the three deps addressed by `edictor[lingpy]`.

**Comment by FredericBlum** [comment] 2024-10-15 09:19
Of course we could go through the script-version of creating this SQLite ( and I know how to do this), but it would be neat to have the workflow readily available through the command line. The syntax is similar for cldf_from_metadata as with the namespace argument, I just can't seem to get the brackets right. I am trying this line in the command line right now:

```zsh
edictor wordlist --dataset=cldf/cldf-metadata.json --name=blumpanoyanomamic --sqlite --namespace={"language_id": "doculect", "concept_name": "concept", "value": "value", "form": "form", "segments": "tokens", "comment": "note", "source_concept": "sourceconcept"}  
```

The goal is to get the column 'Source_Concept' from the forms.csv (as one example), but likely more (e.g. Source_ID). However, I get a parsing error:

```zsh
zsh: parse error near `}'
```

**Comment by LinguList** [comment] 2024-10-16 06:08
Thanks, the example helps.

Try this:
```
edictor wordlist --dataset=cldf/cldf-metadata.json --name=blumpanoyanomamic --sqlite --namespace='{"language_id": "doculect", "concept_name": "concept", "value": "value", "form": "form", "segments": "tokens", "comment": "note", "source_concept": "sourceconcept"}'
```

**Comment by LinguList** [comment] 2024-10-16 06:08
FYI: shell usually allows to put the arg of `--kw`-forms into `" "` quotes or `' '` quotes.

**Comment by FredericBlum** [comment] 2024-10-16 10:26
Ok, so `edictor wordlist` runs through without problems, but I still get an error message when opening the server that `Line «-->» has 1 cells, but we expect 15!`. Not sure what else is wrong. Perhaps something in the config.json? Or is it still the SQLite structure of the database?

**Comment by LinguList** [comment] 2024-10-16 18:51
Can you paste the DB here, or send it to me?

**Comment by LinguList** [comment] 2024-10-16 18:56
Not needed, sorry. I fixed it. You remember, I told you that you should do `chmod 755 blumpanoyanomamic.sqlite3` on the FTP? That fixed it, I think.

**Comment by FredericBlum** [comment] 2024-10-17 08:09
I do now... damn, I forgot about that. Thanks!

**Comment by FredericBlum** [comment] 2024-10-21 11:28
I have to reopen this because it does not seem to work for me. To reproduce:

1. I convert he data to SQLite with the following command:

```shell
edictor wordlist --dataset=cldf/cldf-metadata.json --name=blumpanoyanomamic --sqlite --namespace='{"language_id": "doculect", "concept_name": "concept", "value": "value", "form": "form", "segments": "tokens", "cognacy": "cogids", "comment": "note", "source_concept": "sourceconcept"}
```

2. I connect to the ftp, put the new sqlite and chmod 755 the database.
3. I open `edictor server`. But again, I receive the error message from above regarding the cell problem.

Were there any other changes involved for your fixing of the issue?

**Comment by LinguList** [comment] 2024-10-21 12:41
No, send me the sqlite here please, then I can check!

**Comment by LinguList** [comment] 2024-10-21 12:45
Last time, I think I only did the chmod, nothing else.

**Comment by FredericBlum** [comment] 2024-10-21 12:46
[Archive.zip](https://github.com/user-attachments/files/17460986/Archive.zip)

Here it comes.

**Comment by FredericBlum** [comment] 2024-10-21 12:49
I explicitly checked twice that I run the following commands during the ftp-session:

```shell
put blumpanoyanomamic.sqlite3
chmod 755 blumpanoyanomamic.sqlite3
```

**Comment by LinguList** [comment] 2024-10-21 12:50
I just repeated the same steps.

**Comment by LinguList** [comment] 2024-10-21 12:50
I uploaded the data anew.

**Comment by LinguList** [comment] 2024-10-21 12:52
I even did not do any "chmodding" now.

**Comment by LinguList** [comment] 2024-10-21 13:01
And your sqlite I just uploaded, it also works for me. with your config.

**Comment by LinguList** [comment] 2024-10-21 13:01
without doing any "chmod" this time.

**Comment by FredericBlum** [comment] 2024-10-21 13:03
Your upload worked for me. But counter-test: Can you open my SQLite3? I have re-uploaded my version and again cannot open it with the cell error.

**Comment by LinguList** [comment] 2024-10-21 13:09
It does not work.

**Comment by LinguList** [comment] 2024-10-21 13:12
So something seems to happen with that account that I made there for FTP.

**Comment by LinguList** [comment] 2024-10-21 13:16
I don't know what is going on here. But can it be that the connection is unstable in some way and this breaks the transfer?

**Comment by LinguList** [comment] 2024-10-21 13:18
It seems corruption CAN happen, e.g. if you transfer ascii and not binary (see [here](https://support.hostway.com/hc/en-us/articles/360001126159-FTP-File-corruption-during-ftp-transfer).

**Comment by FredericBlum** [comment] 2024-10-21 13:21
But binary transfer should be standard at MacOS since the introduction of MacOS X, right? I will try to see if I can figure something out.

**Comment by LinguList** [comment] 2024-10-21 13:23
So I think we have identified the following:

- [x] edictor sqlite conversion is okay
- [x] uploading (chmod non chmod da igual) works basically (also from the account)
- [x] corroption happens during upload

So to debug, can you use another means of transferring FTP and test it?

**Comment by FredericBlum** [comment] 2024-10-21 13:29
It seems like I can modify this on the server-side as well for the upload:

```shell
ftp> binary
200 TYPE is now 8-bit binary
ftp> put blumpanoyanomamic.sqlite3 
200 PORT command successful
150 Connecting to port 63523
226-File successfully transferred
226 0.068 seconds (measured here), 1.04 Mbytes per second
73728 bytes sent in 0.000133 seconds (529 Mbytes/s)
```

Now it works! So, before uploading the SQLite3, I have to just type `binary` into the ftp prompt and then everything work's out alright. Thanks for pulling through with me on this one!

**Comment by LinguList** [comment] 2024-10-21 13:52
Going through errors together is essential for programming, I think :-)

**Closed** 2024-10-29 14:30 UTC
